In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

In [2]:
fn = '~/Documents/research/tansey/msk_intern/pyro_model/data/rep-gdsc-ctd2-mean-log.csv'
df = pd.read_csv(fn)

In [3]:
df.sample_id.nunique()

318

In [ ]:
def get_splits(seed, sample_ids, n_folds):
    np.random.seed(seed)
    sample_ids = np.array(df.sample_id.unique())
    perm = np.random.permutation(sample_ids)
    idx = np.round(np.linspace(0, len(sample_ids), n_folds)).astype(int)
    splits = []
for i in range(0, len(idx) - 1):
    start = idx[i]
    end = idx[i + 1]
    splits.append(perm[start:end])
splits

In [4]:
# generate split for

perm

array([162, 205,  78,   1, 139,  43, 287, 136, 216,  18, 159,   7, 239,
        60, 223, 125,  27, 120, 123, 206, 201, 227, 164, 221,  46, 315,
       110, 248, 255, 142, 259, 276, 225, 224, 230, 199, 197, 231, 124,
        88, 292, 134, 284, 247, 126, 195, 295, 241, 169, 261,  56, 171,
       160, 175, 103, 282,  15,  69,  23,  75, 296, 243, 104,  64, 203,
       298, 260, 128, 301,  10,  80,  54,  97,  65, 178, 208,  19, 188,
        41,  59, 266, 132, 200, 204, 281,  40, 269,  32, 157, 118, 267,
       257, 246, 308,  61, 254, 166, 291, 189,  85,  31, 184, 252,  52,
        26, 194, 304, 256,  29, 149, 279, 219,   3, 177, 111, 234, 293,
       235,  48,  47,  96,  98, 233, 264, 278, 209, 174,  62, 220,  99,
       306, 112,  37, 154, 297,  83, 213, 191,  42,  87, 187,  55,  22,
       217, 253, 101,  11, 218, 108, 307,  25, 117,  81, 300, 229, 161,
        82, 156, 198, 262,  74, 145, 130, 113, 286, 288, 294,  28,  24,
       168, 148, 242, 115, 311, 129,  77, 289,  34,  90, 179, 13

In [5]:
idx = np.round(np.linspace(0, len(sample_ids), n_folds)).astype(int)
idx

array([  0,  32,  64,  95, 127, 159, 191, 223, 254, 286, 318])

In [6]:
splits = []
for i in range(0, len(idx) - 1):
    start = idx[i]
    end = idx[i + 1]
    splits.append(perm[start:end])
splits

[array([162, 205,  78,   1, 139,  43, 287, 136, 216,  18, 159,   7, 239,
         60, 223, 125,  27, 120, 123, 206, 201, 227, 164, 221,  46, 315,
        110, 248, 255, 142, 259, 276]),
 array([225, 224, 230, 199, 197, 231, 124,  88, 292, 134, 284, 247, 126,
        195, 295, 241, 169, 261,  56, 171, 160, 175, 103, 282,  15,  69,
         23,  75, 296, 243, 104,  64]),
 array([203, 298, 260, 128, 301,  10,  80,  54,  97,  65, 178, 208,  19,
        188,  41,  59, 266, 132, 200, 204, 281,  40, 269,  32, 157, 118,
        267, 257, 246, 308,  61]),
 array([254, 166, 291, 189,  85,  31, 184, 252,  52,  26, 194, 304, 256,
         29, 149, 279, 219,   3, 177, 111, 234, 293, 235,  48,  47,  96,
         98, 233, 264, 278, 209, 174]),
 array([ 62, 220,  99, 306, 112,  37, 154, 297,  83, 213, 191,  42,  87,
        187,  55,  22, 217, 253, 101,  11, 218, 108, 307,  25, 117,  81,
        300, 229, 161,  82, 156, 198]),
 array([262,  74, 145, 130, 113, 286, 288, 294,  28,  24, 168, 148, 242,
  

In [7]:
for split in splits:
    print(len(split))

32
32
31
32
32
32
32
31
32
32


In [44]:
# save splits to a file

In [45]:
# read in splits from file
# using split_seed, index into correct split
# split dataframe based on that split --> train_df, test_df

In [8]:
split_seed = 2
test_samples = splits[split_seed]
test_df = df.loc[df.sample_id.isin(test_samples)]
train_df = df.loc[~df.sample_id.isin(test_samples)]
# return train_df, test_df